apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: notes
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "django"
        static_configs:
          - targets: ["notes-app-service:8000"]

      - job_name: "mysql"
        static_configs:
          - targets: ["mysql-service:3306"]

      - job_name: "node-exporter"
        static_configs:
          - targets: ["node-exporter:9100"]
