apiVersion: v1
kind: Namespace
metadata:
  name: monitoringapiVersion: v1
  kind: Namespace
  metadata:
      name: monitoringapiVersion: v1
      kind: Namespace
      metadata:
          name: monitoringapiVersion: v1
          kind: Namespace
          metadata:
              name: monitoring
