[notesapp]
ubuntu ansible_host=16.59.144.109
ubuntu ansible_user=ubuntu

[notesapp:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/lenovo/.ssh/notesapp
ansible_host_key_checking=false
